version: "3.3"
services:
  rtmp:
    build: ./rtmp
    ports:
      - "1935:1935"
      - "8080:8080"
      - "8443:8443"
    container_name: rtmp_server
    volumes:
     - ~/SerenidadStream/certs:/certs
  auth:
    build: ./auth
    container_name: auth_server
  certbot:
    image: certbot/certbot
    volumes:
      - /home/username/SerenidadStream/certs:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - rtmp
